export default {
    inventory_list: '.inventory_list',
    burger_menu: "#react-burger-menu-btn",
    inventory_sidebar_link: "#inventory_sidebar_link",
    about_sidebar_link: "#about_sidebar_link",
    logout_sidebar_link: "#logout_sidebar_link",
    reset_sidebar_link: "#reset_sidebar_link",
    social_twitter: "#page_wrapper > footer > ul > li.social_twitter > a",
    social_facebook: "#page_wrapper > footer > ul > li.social_facebook > a",
    social_linkedin: "#page_wrapper > footer > ul > li.social_linkedin > a",
    footer_copy: ".footer_copy",
    sauce_labs_backpack: '[data-test="add-to-cart-sauce-labs-backpack"]',
    sauce_labs_bike_light: '[data-test="add-to-cart-sauce-labs-bike-light"]',
    sauce_labs_bolt_t_shirt: '[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]',
    sauce_labs_fleece_jacket: '[data-test="add-to-cart-sauce-labs-fleece-jacket"]',
    sauce_labs_onesie: '[data-test="add-to-cart-sauce-labs-onesie"]',
    sauce_labs_red_thirt: '[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]',
    remove_sauce_labs_backpack: '[data-test="remove-sauce-labs-backpack"]',
    remove_sauce_labs_bike_light: '[data-test="remove-sauce-labs-bike-light"]',
    remove_sauce_labs_bolt_t_shirt: '[data-test="remove-sauce-labs-bolt-t-shirt"]',
    remove_sauce_labs_fleece_jacket: '[data-test="remove-sauce-labs-fleece-jacket"]',
    remove_sauce_labs_onesie: '[data-test="remove-sauce-labs-onesie"]',
    remove_sauce_labs_red_thirt: '[data-test="remove-test.allthethings()-t-shirt-(red)"]',

}